default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: 123QWEasd

development:
  <<: *default
  database: database_development

 
test:
  <<: *default
  database: database_test

production:
  <<: *default
  database: database_production
